from django.db import models


class actividad(models.Model):
    c_actividad = models.CharField(primary_key=True, max_length=3)
    x_desc_actividad = models.CharField(max_length=60)
    l_publicable = models.CharField(max_length=1)
    l_tipo_actividad = models.CharField(max_length=1)
    l_audiencia = models.CharField(max_length=1)
    l_activo = models.CharField(max_length=1)
    c_actividad_prov = models.CharField(max_length=3)
    l_nuevo = models.CharField(max_length=1)

    def __unicode__(self):
        return self.c_actividad

    class Meta:
        db_table = 'actividad'


class expediente(models.Model):
    n_unico = models.IntegerField(primary_key=True)
    n_incidente = models.IntegerField(primary_key=True)
    c_usuario = models.CharField(max_length=15)
    f_inicio = models.DateTimeField()
    f_termino = models.DateTimeField()
    c_distrito = models.CharField(max_length=3)
    c_provincia = models.CharField(max_length=4)
    c_instancia = models.CharField(max_length=3)
    c_especialidad = models.CharField(max_length=2)
    c_incidente = models.CharField(max_length=3)
    n_unico_relacion = models.IntegerField()
    l_anulado = models.CharField(max_length=1)
    l_acumulado = models.CharField(max_length=1)
    n_nro_exp_origen = models.IntegerField()
    n_ano_exp_origen = models.IntegerField()
    f_auto_apertura = models.DateTimeField()
    f_ing_origen = models.DateTimeField()
    f_incidente = models.DateTimeField()
    x_sumilla = models.CharField(max_length=600)
    f_denuncia = models.DateTimeField()
    n_denuncia = models.CharField(max_length=150)
    n_atestado = models.CharField(max_length=150)
    f_anulado = models.DateTimeField()
    x_anulado = models.CharField(max_length=100)
    l_parte_interpone = models.CharField(max_length=1)
    n_ventanilla = models.IntegerField()
    n_sec_ingreso = models.IntegerField()
    n_ano_ingreso = models.IntegerField()
    l_servidor = models.CharField(max_length=1)
    l_exp_agrario = models.CharField(max_length=1)
    l_devolver_ejec = models.CharField(max_length=1)
    c_instancia_ejec = models.CharField(max_length=3)
    f_devuelto_ejec = models.DateTimeField()
    n_cedulas = models.IntegerField()
    x_tasa_judicial = models.CharField(max_length=255)
    c_ind_modifica = models.CharField(max_length=1)
    c_cod_archivo = models.CharField(max_length=15)
    c_cod_visualiza = models.CharField(max_length=1)
    c_cod_medida_cautelar = models.CharField(max_length=6)
    l_archivo = models.CharField(max_length=1)
    x_observacion = models.CharField(max_length=200)
    x_nombre_fiscal = models.CharField(max_length=70)
    x_fiscalia = models.CharField(max_length=70)
    x_oficina_fiscal = models.CharField(max_length=15)
    f_hecho = models.DateTimeField()
    l_tipo_registro = models.CharField(max_length=1)
    n_juz_exp_origen = models.IntegerField()
    f_registro = models.DateTimeField()
    x_secretario = models.CharField(max_length=100)
    f_ult_modificacion = models.DateTimeField()
    c_usu_ult_modi = models.CharField(max_length=15)
    l_confrontado = models.CharField(max_length=1)
    f_confrontacion = models.DateTimeField()
    c_usu_confrontacion = models.CharField(max_length=15)
    x_ape_secretario_antiguo = models.CharField(max_length=50)
    x_secretario_antiguo = models.CharField(max_length=60)
    l_cond = models.CharField(max_length=1)
    n_exp_sala = models.IntegerField()
    n_ano_sala = models.CharField(max_length=4)
    c_c_codprovincia = models.IntegerField()
    c_c_coddistrito = models.IntegerField()
    c_etapa = models.CharField(max_length=3)
    c_estado = models.CharField(max_length=3)
    c_materia = models.CharField(max_length=3)
    c_ubicacion = models.CharField(max_length=2)
    c_pos_usuario = models.CharField(max_length=15)
    n_exp_sala_ant = models.IntegerField()
    n_ano_sala_ant = models.CharField(max_length=4)
    f_origen_sala = models.DateTimeField()
    c_secretario = models.CharField(max_length=15)
    n_unico_juz = models.IntegerField()
    n_incidente_juz = models.IntegerField()
    x_desc_cedula = models.CharField(max_length=255)
    c_ubigeo_fiscalia = models.CharField(max_length=10)
    n_ano_exp_juz = models.CharField(max_length=4)
    n_procedencia_juz = models.IntegerField()
    n_tip_procedencia_juz = models.CharField(max_length=2)
    c_distrito_juz = models.CharField(max_length=3)
    c_provincia_juz = models.CharField(max_length=4)
    n_cuantia = models.IntegerField()
    moneda_cuantia = models.CharField(max_length=2)
    n_inc_exp_juz = models.IntegerField()
    n_nro_exp_salas = models.IntegerField()
    n_ano_exp_salas = models.CharField(max_length=4)
    n_inc_exp_salas = models.IntegerField()
    n_procedencia_salas = models.IntegerField()
    n_tip_procedencia_salas = models.CharField(max_length=2)
    c_distrito_salas = models.CharField(max_length=3)
    c_provincia_salas = models.CharField(max_length=4)
    f_apelado_salas = models.DateTimeField()
    x_fallo_salas = models.CharField(max_length=500)
    n_oficio_elevado_salas = models.CharField(max_length=80)
    l_es_carcel = models.CharField(max_length=1)
    x_desc_depositoj = models.CharField(max_length=255)
    x_juez = models.CharField(max_length=180)
    n_nro_exp_juz = models.IntegerField()
    n_nro_en_juzgado = models.IntegerField()
    n_ano_en_juzgado = models.IntegerField()
    f_aud = models.DateTimeField()
    b_aud = models.CharField(max_length=1)
    c_aud_uid = models.CharField(max_length=30)
    c_aud_uidred = models.CharField(max_length=30)
    c_aud_pc = models.CharField(max_length=30)
    n_aud_ip = models.CharField(max_length=15)
    c_aud_mcaddr = models.CharField(max_length=17)
    n_tasas = models.IntegerField()
    n_deposito = models.IntegerField()
    f_etapa = models.DateTimeField()
    f_estado = models.DateTimeField()
    c_usuario_asignadoa = models.CharField(max_length=15)
    f_usuario_asignadoa = models.DateTimeField()
    f_materia = models.DateTimeField()
    f_ubicacion = models.DateTimeField()
    c_usuario_actual = models.CharField(max_length=15)
    f_usuario_actual = models.DateTimeField()
    x_motivo_reasignacion = models.CharField(max_length=200)
    c_sede = models.CharField(max_length=4)
    c_ubigeo_hecho = models.CharField(max_length=10)
    c_fiscalia = models.CharField(max_length=5)
    x_exp_duplicados = models.CharField(max_length=255)
    l_autoriza_prev = models.CharField(max_length=1)
    n_copias = models.IntegerField()
    c_perfil = models.CharField(max_length=2)
    c_org_delito = models.CharField(max_length=2)
    c_delito = models.CharField(max_length=3)
    c_ubigeo = models.CharField(max_length=10)
    c_org_jurisd = models.CharField(max_length=2)
    c_instancia_ori = models.CharField(max_length=3)
    l_elevacion = models.CharField(max_length=1)
    c_incidente_old = models.CharField(max_length=3)
    c_distrito_ori = models.CharField(max_length=3)
    c_provincia_ori = models.CharField(max_length=4)
    l_ind_previo = models.CharField(max_length=1)
    c_nivel_instancia = models.CharField(max_length=1)
    l_union = models.CharField(max_length=1)
    l_tipo_juzgado_exp = models.CharField(max_length=1)
    l_ind_cuantia_completo = models.CharField(max_length=1)
    l_ind_cuantia_indeterminado = models.CharField(max_length=1)
    n_tipo_cambio = models.IntegerField()
    c_es_exhorto = models.CharField(max_length=1)
    c_tipo_exhorto = models.CharField(max_length=1)
    c_es_remate_jud = models.CharField(max_length=1)
    c_tipo_remate_jud = models.CharField(max_length=2)
    l_ind_notifi_completo = models.CharField(max_length=1)
    l_ind_sin_arancel = models.CharField(max_length=1)
    l_ind_sin_notif = models.CharField(max_length=1)
    l_ind_inv = models.CharField(max_length=1)
    l_ind_exp = models.CharField(max_length=3)
    c_item = models.CharField(max_length=3)
    c_letra = models.CharField(max_length=2)
    x_formato = models.CharField('Expediente', max_length=50)
    n_sub_tema_id = models.IntegerField()
    x_anaquel = models.CharField(max_length=60)
    l_derivado_juz_perif = models.CharField(max_length=1)

    def __unicode__(self):
        return self.x_formato

    class Meta:
        db_table = 'expediente'


class ubicacion_expediente(models.Model):
    c_org_jurisd = models.CharField(max_length=2)
    c_org_jurisd_destino = models.CharField(max_length=2)
    c_ubicacion = models.CharField(max_length=2)
    l_activo = models.CharField(max_length=1)
    l_fuera = models.CharField(max_length=1)
    l_tip_archivo = models.CharField(max_length=1)
    ubc_id = models.CharField(max_length=6)
    x_desc_ubicacion = models.CharField(max_length=90)

    class Meta:
        db_table = 'ubicacion_expediente'

        