#-*- coding: utf-8 -*-
from django.db import models

class usuario(models.Model):
    c_usuario = models.CharField(primary_key=True)
    l_tipo_usuario = models.CharField(max_length=1)
    x_nom_usuario = models.CharField(max_length=50)
    n_nro_exp = models.IntegerField()
    c_equipo = models.CharField(max_length=2)
    l_conectado = models.CharField(max_length=1)
    c_clave = models.CharField(max_length=10)
    c_foto_check = models.CharField(max_length=12)
    c_perfil = models.CharField(max_length=2)
    n_temporizador = models.IntegerField()
    fec_cambio_clave = models.DateTimeField()
    num_dias_clave = models.IntegerField()
    c_clave_vocal = models.CharField(max_length=15)
    l_tipo_redist = models.CharField(max_length=1)
    c_distrito = models.CharField(max_length=3)
    c_provincia = models.CharField(max_length=4)
    c_sede = models.CharField(max_length=4)
    l_activo = models.CharField(max_length=1)
    l_recibe_carga = models.CharField(max_length=1)
    l_ind_print = models.CharField(max_length=1)
    f_aud = models.DateTimeField()
    b_aud = models.CharField(max_length=1)
    c_aud_uid = models.CharField(max_length=30)
    c_aud_uidred = models.CharField(max_length=30)
    c_aud_pc = models.CharField(max_length=30)
    n_aud_ip = models.CharField(max_length=15)
    c_aud_mcaddr = models.CharField(max_length=17)
    n_carga_procesal = models.IntegerField()
    n_grupo = models.IntegerField()
    l_antiguedad = models.IntegerField()
    l_ultimo_asig = models.CharField(max_length=1)
    l_usuario_grj = models.CharField(max_length=1)
    c_dni = models.CharField(max_length=8)
    c_ape_paterno = models.CharField(max_length=40)
    c_ape_materno = models.CharField(max_length=40)
    c_nombres = models.CharField(max_length=60)
    f_nac = models.DateTimeField()
    c_flag_valid_reniec = models.CharField(max_length=1)
    l_correo = models.CharField(max_length=1)
    x_desc_correo = models.CharField(max_length=40)
    l_sij_reniec = models.CharField(max_length=1)
    f_reg_reniec = models.DateTimeField()
    l_ofic_reniec = models.CharField(max_length=1)
    c_clave_dje = models.CharField(max_length=15)
    l_logeado_sij = models.CharField(max_length=1)
    l_sesion_multiple = models.CharField(max_length=1)
    x_ip_address_log = models.CharField(max_length=30)
    x_mc_address_log = models.CharField(max_length=30)
    x_usuario_red_log = models.CharField(max_length=30)

    def __unicode__(self):
        return self.c_usuario

    class Meta:
        db_table = 'usuario'
        unique_together = (('c_usuario', 'c_distrito', 'c_provincia', 'c_sede'),)
            #unique_together = (('c_distrito', 'c_instancia'),)
